version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: hr-postgres
    restart: always
    environment:
      POSTGRES_DB: hris_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./hr_backend
    container_name: hr-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hris_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - ./hr_backend/uploads:/app/uploads
      - C:/attendance:/app/attendance

  frontend:
    build: ./hr-frontend
    container_name: hr-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data: